# Generated by Django 4.1.7 on 2023-05-06 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='is_breakfast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='is_confection',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='is_dinner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='is_lunch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='is_snack',
            field=models.BooleanField(default=False),
        ),
    ]
